### ISSUE TITLE
How to authorize preapproval keys

### ISSUE THREAD

**Issue by cmezak** [jpablobr/active_paypal_adaptive_payment#14]
So, I've been able to use the preapprove_payment method to get a preapproval key, but the sender has to authorize it before I can use it to capture funds (I assume through execute_payment). Other ActiveMerchant gateways have a redirect_url_for([token]) method that I can use to get the paypal url where the sender can approve payment. Is there a similar method for this adaptive gateway?

I've created a stack overflow question for this problem [here](http://stackoverflow.com/questions/9788263/authorizing-a-preapproved-payment-key-with-active-paypal-adaptive-payment-gem).

**Comment by jpablobr** [comment]
I feel your pain :/ but that is very paypay/rails specific logic and kind of out of the scope of this gem. 

That said, are you using spree? if so, your controller has to look kind of like this?

https://github.com/spree/spree_paypal_express/blob/master/app/controllers/spree/checkout_controller_decorator.rb

That's based on PayPal Express, but it's a bit similar. I've been trying open-source a decent version of the PayPal Adaptive payments for spree [here](https://github.com/jpablobr/spree_paypal_adaptive_payment), but haven't got the time to finish it. :disappointed:

Hope that makes scene and helps you a bit, anything else just post it here and I'll try to help as much as possible.

**Comment by cmezak** [comment]
I've figured out how to put the URL together. It's 
    "https://www.sandbox.paypal.com/webscr?cmd=_ap-preapproval&preapprovalkey=" + @payment.preapproval_key

Then I have to go through the source to figure out how to assemble the options hash for preapprove_payment. If I can, when I'm through with all of this, I'll contribute to the documentation and code.

**Comment by jpablobr** [comment]
That URL is already being handled by the gem [here](https://github.com/jpablobr/active_paypal_adaptive_payment/blob/master/lib/active_merchant/billing/gateways/paypal_adaptive_payment.rb#L31).

Basically this is how a payment process should look like:

1) Process the payment/order in your checkout_controller#payment action:

``` ruby
# req = the Hash with all the order/payment required options.
session[:adaptive_payment_response] = gateway.setup_purchase(req)
```

2) Then `session[:adaptive_payment_response]` should be full of a bunch
of PayPal info/crap regarding that first payment request. 

3) You then - in that #payment action - need to verify if its successfull.

``` ruby
if session[:adaptive_payment_response].success?
  # confirmation key for the second request
  redirect_to (gateway.redirect_url_for(session[:adaptive_payment_response][:pay_key])) # redirecting again...
else
  gateway_error(session[:adaptive_payment_response])
  redirect_to edit_order_checkout_url
end
```

4) Now you need another `checkout_controller#action` to receive what PayPal
is - again - sending you. The last and confirmed request.

5) profit :/

**Comment by cmezak** [comment]
Hi jpablobr,

Thanks for taking the time to explain this, but I'm not sure if it fits with what I'm doing.

On my site, users can request to receive periodic automatic orders of our products, so I need to set up the a pre approved payment agreement. I don't need to actually execute a payment at this point, just to set up the preapproval agreement so I can do the automatic payments in the future.

The first step is to use preapprove_payment to get the preapproval key. Then I have to send the user to paypal with the key so they can log into paypal and approve it. That's what I figured out in my previous post. I actually saw that url in the source code, but how am I supposed to use it in my code?

Once the user has authorized the preapproves payment key, I get an IPN to let my site know that it's been authorized. From the on, I should be able to use the key to make purchases without needing the user to log in. Haven't tried to figure that one out yet, though. : )

I'm loosely basing my approach to this on ryanb's railscasts for integrating paypal into a rails app.

**Comment by jpablobr** [comment]
I haven't played much with `preapprove_payment`, but it should have to be similar to the other requests.

The `gateway.setup_purchase(req)` ([`setup_purchase`](https://github.com/jpablobr/active_paypal_adaptive_payment/blob/master/lib/active_merchant/billing/gateways/paypal_adaptive_payment.rb#L42)) will [build](https://github.com/jpablobr/active_paypal_adaptive_payment/blob/master/lib/active_merchant/billing/gateways/paypal_adaptive_payment.rb#L100) the request which in turn will give you the `key`.

Then, the [`redirect_url_for`](https://github.com/jpablobr/active_paypal_adaptive_payment/blob/master/lib/active_merchant/billing/gateways/paypal_adaptive_payment_common.rb#L18) (in this case using Rail's `redirect_to`):

``` ruby
redirect_to (gateway.redirect_url_for(session[:adaptive_payment_response][:pay_key]))
```

will send the user to PayPal's website to handle the specified type of request (in your case a `preapprove_payment`). Once in there, based on what the user did, PayPal will send to your application one last "response" basically containing those user actions.

All these in the same way I mentioned on my previous comment.

One more caveat... that last request is not an IPN. IPNs are handled differently. However, the IPN is not required... but is obviously helpful since that will let your application know the status of the whole transaction. Basically without it you are blind, but the `preapprove_payment` (successful or not) will be "successfully" completed (if the user accepted it or not). <3 PayPal :trollface:

**Comment by jpablobr** [comment]
Hey I'm closing the issue since this is not specific to the gem... Feel free to open it again if you think is necessary.
